debian:
  image: debian:unstable
  stage: build
  script:
    - apt update 
    - apt install meson gcc valac --no-install-recommends -y
    - apt install libarchive-dev libreadline-dev --no-install-recommends -y
    - meson build -Ddebug=true
    - ninja -C build
    - cd build && ./inary-test || true



alpine:
  image: alpine:latest
  stage: build
  script:
    - apk update 
    - apk add meson musl-dev gcc bash vala glib-dev glib-static readline-dev libarchive-dev
    - meson build -Ddebug=true -Dstatic=true
    - ninja -C build
    - cd build && ./inary-test || true
