debian:
  image: debian:unstable
  stage: build
  artifacts:
    expire_in: 1 week
    paths: 
      - build
  script:
    - apt update 
    - apt install meson gcc valac --no-install-recommends -y
    - apt install libarchive-dev libreadline-dev --no-install-recommends -y
    - meson build -Ddebug=true
    - ninja -C build
    - cd build && ./inary-test || true



alpine:
  image: alpine:latest
  stage: build
  artifacts:
    expire_in: 1 week
    paths:
      - build
  script:
    - apk update 
    - apk add meson musl-dev gcc bash vala glib-dev readline-dev libarchive-dev upx
    - apk add libarchive-static readline-static glib-static zlib-static ncurses-static acl-static expat-static openssl-libs-static xz-dev zstd-static lz4-static bzip2-static
    - meson build -Ddebug=true -Dstatic=true
    - ninja -C build
    - upx -9 build/* || true
    - cd build && ./inary-static || true
