image: debian:unstable

debian:
  stage: build
  script:
    - apt update 
    - apt install meson gcc valac --no-install-recommends -y
    - apt install libarchive-dev libreadline-dev --no-install-recommends -y
    - meson build -Ddebug=true
    - ninja -C build
    - cd build && ./inary-test || true


image: alpine:latest

alpine:
  stage: build
  script:
    - apk update 
    - apk add meson gcc vala glib libarchive -y
    - meson build -Ddebug=true
    - ninja -C build
    - cd build && ./inary-test || true
